/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.samza.task.sql;

import java.util.List;

import org.apache.samza.sql.api.data.EntityName;
import org.apache.samza.sql.api.data.Relation;
import org.apache.samza.sql.api.data.Tuple;
import org.apache.samza.task.MessageCollector;


/**
 * This class defines the interface class to be used by the operators to send their output via runtime system resources,
 * s.t. the output system streams, the system storage, or <code>OperatorRouter</code>.
 *
 */
public interface SqlMessageCollector extends MessageCollector {

  /**
   * This method allows the current operator send its relation output to next
   *
   * @param deltaRelation The delta <code>Relation</code> output generated by the current operator
   * @throws Exception Throws exception if failed
   */
  void send(Relation deltaRelation) throws Exception;

  /**
   * This method allows the current operator send its tuple output to next
   *
   * @param tuple The <code>Tuple</code> object generated by the current operator
   * @throws Exception Throws exception if failed
   */
  void send(Tuple tuple) throws Exception;

  /**
   * This method allows the current operator triggers timeout actions via the <code>SqlMessageCollector</code>.
   *
   * <p>This method sets timeout events to the corresponding <code>outputEntities</code> s.t. the next operators
   * attached to those entities will be notified of the timeout.
   *
   * @param outputEntities The list of output entities via which the timeout event needs to be sent to
   * @throws Exception Throws exception if failed
   */
  void timeout(List<EntityName> outputEntities) throws Exception;

}
