# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
permalink: /:categories/:title
name: Samza
highlighter: pygments
markdown: redcarpet
exclude: ['_notes']
redcarpet:
  extensions: ['with_toc_data', 'smart', 'strikethrough', 'tables']
exclude: [_docs]
baseurl: http://samza.apache.org
version: latest
# this is the version you will go if you click 'switch version' in "latest" pages.
latest-release: '0.14'
collections:
  menu:
    output: false
  news:
    output: true
  case-studies:
    output: true
  talks:
    output: false
  meetups:
    output: false
  committers:
    output: false
  releases:
    output: true
  powered-by:
    output: false